FROM registry.k8s.io/ingress-nginx/controller:v1.3.0@sha256:d1707ca76d3b044ab8a28277a2466a02100ee9f58a86af1535a3edf9323ea1b5
#FROM quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.30.0 
MAINTAINER lin01 <lin@gmail.com>
