FROM k8s.gcr.io/ingress-nginx/controller:v0.46.0@sha256:52f0058bed0a17ab0fb35628ba97e8d52b5d32299fbc03cc0f6c7b9ff036b61a
#FROM quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.30.0 
MAINTAINER lin01 <lin@gmail.com>
