FROM registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.1.1@sha256:64d8c73dca984af206adf9d6d7e46aa550362b1d7a01f3a0a91b20cc67868660 
#FROM quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.30.0 
MAINTAINER lin01 <lin@gmail.com>
